<a href="https://colab.research.google.com/github/shinnew99/Apziva-Projects/blob/main/Project1-HappyCustomers/2ndNote.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 2nd Try (~ until July 23th):
1. Apply 'Lazy Classifier' (O)
2. Choose 3 models, using the report and should able to explain the reasons for choosing those models so that I can justify my reason! ( )
3. Train the models separately (O)
4. Use the 'gridsearch' and 'randomsearch', check if these can improve the model performances (O)
5. Focus on Recall for class0, because it is more important to know why unsatisfied customers are unsatisfied. ( )

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install lazypredict

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.9/190.9 MB 5.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.3.1+cu121 requires nvidia-cublas-cu12==12.1.3.1; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cuda-cupti-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cuda-nvrtc-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cuda-runtime-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cudnn-cu12==8.9.2.26; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requ

In [ ]:
import os
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split

from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.svm import LinearSVC

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

## Data Import

In [ ]:
# Read dataset
df = pd.read_csv('/content/drive/MyDrive/Apziva/ACME-HappinessSurvey2020.csv')

data = df[['X1', 'X2', 'X3', 'X4', 'X5', 'X6']]
target = df[['Y']]

In [ ]:
# seed = random.randint(1000, 9999)
seed = 6245
print(seed)

6245


### Data Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=seed)

## Lazy Classifier

In [ ]:
clf = LazyClassifier(verbose=0, ignore_warnings = True, custom_metric=None) # force_col_wise=True
models, predictions = clf.fit(X_train, X_test, y_train, y_test)
models

100%|██████████| 29/29 [00:05<00:00,  5.68it/s]

[LightGBM] [Info] Number of positive: 51, number of negative: 49
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000222 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 31
[LightGBM] [Info] Number of data points in the train set: 100, number of used features: 6
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.510000 -> initscore=0.040005
[LightGBM] [Info] Start training from score 0.040005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain:

Accuracy  Balanced Accuracy  ROC AUC  F1 Score  \
Model                                                                           
LabelPropagation                   0.69               0.71     0.71      0.70   
LabelSpreading                     0.69               0.71     0.71      0.70   
BernoulliNB                        0.62               0.69     0.69      0.62   
LGBMClassifier                     0.58               0.66     0.66      0.58   
DecisionTreeClassifier             0.65               0.65     0.65      0.67   
BaggingClassifier                  0.65               0.65     0.65      0.67   
QuadraticDiscriminantAnalysis      0.58               0.62     0.62      0.59   
NuSVC                              0.65               0.61     0.61      0.66   
NearestCentroid                    0.54               0.60     0.60      0.55   
SVC                                0.54               0.60     0.60      0.55   
GaussianNB                         0.54               0.60     0.60      0.55   
ExtraTreeClassifier                0.58               0.56     0.56      0.59   
RidgeClassifierCV                  0.50               0.53     0.53      0.52   
RidgeClassifier                    0.50               0.53     0.53      0.52   
AdaBoostClassifier                 0.50               0.53     0.53      0.52   
LogisticRegression                 0.50               0.53     0.53      0.52   
LinearDiscriminantAnalysis         0.50               0.53     0.53      0.52   
CalibratedClassifierCV             0.50               0.53     0.53      0.52   
LinearSVC                          0.50               0.53     0.53      0.52   
RandomForestClassifier             0.54               0.53     0.53      0.56   
XGBClassifier                      0.54               0.53     0.53      0.56   
DummyClassifier                    0.69               0.50     0.50      0.57   
ExtraTreesClassifier               0.54               0.49     0.49      0.55   
SGDClassifier                      0.35               0.49     0.49      0.27   
Perceptron                         0.50               0.47     0.47      0.52   
KNeighborsClassifier               0.42               0.34     0.34      0.43   
PassiveAggressiveClassifier        0.27               0.30     0.30      0.28   

                               Time Taken  
Model                                      
LabelPropagation                     0.10  
LabelSpreading                       0.11  
BernoulliNB                          0.12  
LGBMClassifier                       0.14  
DecisionTreeClassifier               0.18  
BaggingClassifier                    0.26  
QuadraticDiscriminantAnalysis        0.11  
NuSVC                                0.18  
NearestCentroid                      0.09  
SVC                                  0.05  
GaussianNB                           0.14  
ExtraTreeClassifier                  0.16  
RidgeClassifierCV                    0.04  
RidgeClassifier                      0.04  
AdaBoostClassifier                   0.38  
LogisticRegression                   0.15  
LinearDiscriminantAnalysis           0.17  
CalibratedClassifierCV               0.35  
LinearSVC                            0.09  
RandomForestClassifier               0.36  
XGBClassifier                        0.44  
DummyClassifier                      0.12  
ExtraTreesClassifier                 0.76  
SGDClassifier                        0.04  
Perceptron                           0.10  
KNeighborsClassifier                 0.14  
PassiveAggressiveClassifier          0.10

## Modeling Part 1
### Model 1 - ExtraTreeClassifier
I choose this model because it showed the highest f1 score at 1st run.

In [ ]:
model1 = ExtraTreesClassifier(random_state = seed)
model1.fit(X_train, y_train)

ExtraTreesClassifier(random_state=6245)

#### GridSearch & RandomSearch for Model1

In [ ]:
# Setting up hyperparameter grid
param_grid = {
    'max_depth': [3, 5, 7, 10], # I picked odd numbers rather than even numbers, because the tree shows the hierarchy
    'n_estimators': [10, 50, 100, 200]
}
# Try to write the reasons right away next to the code so that I can remember, and explain better to the other people (esp in industries).

grid_search1 = GridSearchCV(model1, param_grid, cv=5)
grid_search1.fit(X_train, y_train)


# Print out the most optimized parameter score
print("Best Parameters: ", grid_search1.best_params_)
print("Best Score: ", grid_search1.best_score_)

Best Parameters:  {'max_depth': 5, 'n_estimators': 200}
Best Score:  0.62


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_dist = {
    'max_depth': randint(1, 11),
    'n_estimators': randint(10, 201)
}

# Random Search
random_search1 = RandomizedSearchCV(model1, param_distributions=param_dist, n_iter=20, cv=5)
random_search1.fit(X_train, y_train)

# Print out the most optimized parameter score
print("Best Parameters: ", random_search1.best_params_)
print("Best Score: ", random_search1.best_score_)

Best Parameters:  {'max_depth': 5, 'n_estimators': 124}
Best Score:  0.62


In [ ]:
predictions1 = model1.predict(X_test)

In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, predictions1)
conf_matrix = confusion_matrix(y_test, predictions1)
class_report = classification_report(y_test, predictions1)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.5769230769230769
Confusion Matrix:
[[ 4  4]
 [ 7 11]]
Classification Report:
              precision    recall  f1-score   support

           0       0.36      0.50      0.42         8
           1       0.73      0.61      0.67        18

    accuracy                           0.58        26
   macro avg       0.55      0.56      0.54        26
weighted avg       0.62      0.58      0.59        26



### Model2 - RandomForest

I choose this model because RandomForest is an ensembling learning algorithm for binary classification task

In [ ]:
model2 = RandomForestClassifier(random_state = seed)
model2.fit(X_train, y_train)

RandomForestClassifier(random_state=6245)

#### GridSearch & RandomSearch for Model2

In [ ]:
from sklearn.model_selection import GridSearchCV

# Setting up hyperparameter grid
param_grid = {
    'max_depth': [3, 5, 7, 10],
    'n_estimators': [10, 50, 100, 200]
}

grid_search2 = GridSearchCV(model2, param_grid, cv=5)
grid_search2.fit(X_train, y_train)


# Print out the most optimized parameter score
print("Best Parameters: ", grid_search2.best_params_)
print("Best Score: ", grid_search2.best_score_)

Best Parameters:  {'max_depth': 10, 'n_estimators': 10}
Best Score:  0.6499999999999999


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_dist = {
    'max_depth': randint(1, 11),
    'n_estimators': randint(10, 201)
}


# Random Search
random_search2 = RandomizedSearchCV(model2, param_distributions=param_dist, n_iter=20, cv=5)
random_search2.fit(X_train, y_train)

# Print out the most optimized parameter score
print("Best Parameters: ", random_search2.best_params_)
print("Best Score: ", random_search2.best_score_)

Best Parameters:  {'max_depth': 3, 'n_estimators': 83}
Best Score:  0.5700000000000001


In [ ]:
predictions2 = model2.predict(X_test)

In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, predictions2)
conf_matrix = confusion_matrix(y_test, predictions2)
class_report = classification_report(y_test, predictions2)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.5769230769230769
Confusion Matrix:
[[ 4  4]
 [ 7 11]]
Classification Report:
              precision    recall  f1-score   support

           0       0.36      0.50      0.42         8
           1       0.73      0.61      0.67        18

    accuracy                           0.58        26
   macro avg       0.55      0.56      0.54        26
weighted avg       0.62      0.58      0.59        26



### Model3 - LinearSVC

In [ ]:
model3 = LinearSVC(random_state = seed)
model3.fit(X_train, y_train)

LinearSVC(random_state=6245)

In [ ]:
predictions3 = model3.predict(X_test)

In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, predictions3)
conf_matrix = confusion_matrix(y_test, predictions3)
class_report = classification_report(y_test, predictions3)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.5
Confusion Matrix:
[[ 5  3]
 [10  8]]
Classification Report:
              precision    recall  f1-score   support

           0       0.33      0.62      0.43         8
           1       0.73      0.44      0.55        18

    accuracy                           0.50        26
   macro avg       0.53      0.53      0.49        26
weighted avg       0.61      0.50      0.52        26



### Model4 - LogisticRegression

In [ ]:
model4 = LogisticRegression(random_state = seed)
model4.fit(X_train, y_train)

LogisticRegression(random_state=6245)

In [ ]:
predictions4 = model4.predict(X_test)

In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, predictions4)
conf_matrix = confusion_matrix(y_test, predictions4)
class_report = classification_report(y_test, predictions4)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)


Accuracy: 0.5
Confusion Matrix:
[[ 5  3]
 [10  8]]
Classification Report:
              precision    recall  f1-score   support

           0       0.33      0.62      0.43         8
           1       0.73      0.44      0.55        18

    accuracy                           0.50        26
   macro avg       0.53      0.53      0.49        26
weighted avg       0.61      0.50      0.52        26



### Model5 - DecisionTreeClassifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier

clf_tree = DecisionTreeClassifier(min_samples_split=0.2, random_state = seed)
clf_tree.fit(X_train, y_train)
pred = clf_tree.predict(X_train)
print('Training Report\n {}'.format(classification_report(y_train,pred)))
print('Training accuracy: {:.3f}'.format(accuracy_score(y_train,pred)))

Training Report
               precision    recall  f1-score   support

           0       0.79      0.69      0.74        49
           1       0.74      0.82      0.78        51

    accuracy                           0.76       100
   macro avg       0.76      0.76      0.76       100
weighted avg       0.76      0.76      0.76       100

Training accuracy: 0.760


### Conclusions after 2nd Try:

1. When doing GridSearch and RandomSearch, I need to tuned each hyperparameters. Model 3, LinearSVC and Model 4 Logistic also goes compatible with Grid and RandomSearch; I didn't tuned them and maybe that's why I got error.
2. Since the tree shows the hierarchy, odd numbers are better than even numbers for ranking.
3. The performance did imporved but didnt reached to 73, so I pondered hard and finally tried another model which was DeicisionClassifier. It eventually worked!
4. I erase scaler which might affect performance
5. Setting up an random_seed might also affect performance
